export const EvidenceType = Object.freeze({
  RESOURCE_STATE: "RESOURCE_STATE",

  CONTAINER_STATUS: "CONTAINER_STATUS",

  OWNER_CHAIN: "OWNER_CHAIN",

  NODE_CONTEXT: "NODE_CONTEXT",

  KUBERNETES_EVENT: "KUBERNETES_EVENT",

  CONTAINER_LOG: "CONTAINER_LOG",
});
