apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubedoctor-pending-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubedoctor-pending-test
  template:
    metadata:
      labels:
        app: kubedoctor-pending-test
    spec:
      containers:
        - name: pending-test
          image: busybox:1.36
          resources:
            requests:
              cpu: "100"
              memory: "1Ti"
          command: ["sh", "-c", "sleep 3600"]
